# Generated by Django 6.1 on 2026-09-05 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('interval_seconds', models.PositiveBigIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('current_status', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('UP', 'Up '), ('DEGRADED', 'Degraded'), ('DOWN', 'Down'), ('RECOVERED', 'Recovered')], default='UNKNOWN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='users.user')),
            ],
        ),
    ]
